name: 'Build Image'

on:
  push:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: 'samekan052'
            users: 'samekan822,samekan1'
          - name: 'kashiwa052'
            users: 'Hytusx,KashEight'
          - name: 'karasu052'
            users: 'bakarasukun'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2

      - name: Login to Registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          registry: 'ghcr.io'
          username: '${{ github.repository_owner }}'
          password: '${{ secrets.GITHUB_TOKEN }}'

      - name: Prepare Image Metadata
        id: metadata
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # v4.6.0
        with:
          images: 'ghcr.io/slashnephy/${{ matrix.name }}'
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build Image & Push
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3
        with:
          push: true
          file: ci.Dockerfile
          tags: '${{ steps.metadata.outputs.tags }}'
          labels: '${{ steps.metadata.outputs.labels }}'
          cache-from: 'type=gha'
          cache-to: 'type=gha,mode=max'
          build-args: |
            USERS=${{ matrix.users }}
            TWITTER_CK=${{ secrets.TWITTER_CK }}
            TWITTER_CS=${{ secrets.TWITTER_CS }}
            TWITTER_AT=${{ secrets.TWITTER_AT }}
            TWITTER_ATS=${{ secrets.TWITTER_ATS }}
